#
# Makefile
#

prefix = /usr/local
includedir = $(prefix)/include

headers = libbackup_common.h

install:
	install -D -g root -m 0644 -o root -t $(includedir)/backup $(headers)

# vi: set noexpandtab sw=4 ts=4:
