#!/bin/sh

lock_pid=/etc/mtab~$$
lock=/etc/mtab~

lock_mtab()
{
	if ! touch $lock_pid || ! ln $lock_pid $lock || ! rm $lock_pid; then
		echo "Error accessing /etc/mtab"
		exit 1
	fi
}

unlock_mtab()
{
	rm $lock
}

# vi: set noexpandtab sw=4 ts=4:
