#!/usr/bin/env bash

get_bundle_path()
{
    bundle_path=$(git config user.bundleIn)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

get_bundles()
{
    bundles=$(ls $1/$reponame.* 2>/dev/null)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

set -e

rootdir=$(git rev-parse --show-toplevel)
[[ $? != 0 ]] && exit 1
reponame=$(basename $rootdir)

get_bundle_path
get_bundles $bundle_path

for b in $bundles; do
    f=$(basename $b)
    if [[ $f == "$reponame.bundle" ]]; then
        echo "Importing bundle $f"
        mv $b $rootdir/../.$f
        git fetch bundle
    else
        echo "Importing branch bundle $f"
        mv $b $rootdir/..
        bname=$(echo $f | cut -d '.' -f 2)
        [[ ($? == 0) && (-n $bname) ]] || exit 1
        echo "Creating remote bundle_$bname"
        git remote add bundle_$bname ../$f
        git fetch bundle_$bname
    fi
done
