#!/usr/bin/env bash

get_branches()
{
    local tmp

    tmp=$(git branch)
    if [[ $? != 0 ]]; then
        return 1
    fi

    while IFS= read -r line; do
        branches+="${line##??} "
    done < <(echo "$tmp")
}

set -e

get_branches

set +e

ret=0
for b in $branches; do
    if [[ $b != "master" ]]; then
        cmd="git checkout $b && git reset --hard origin/$b"
        echo "Running \"$cmd\""
        read -p "Continue? (y/n) " resp
        if [[ $resp = "y" ]]; then
            eval $cmd || ret=1
        fi
    fi
done

git checkout master

exit $ret
