#!/bin/sh

set -e

tmpdir=/tmp/git_verify_archive

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" >&2
    exit 1
fi

while getopts p: opt; do
    case $opt in
        p)
            path=$OPTARG;;
        *)
            exit 1;;
    esac
done

if [ $OPTIND -lt $# ]; then
    echo "Unrecognized arguments" >&2
    exit 1
fi

if [ $OPTIND -gt $# ]; then
    echo "Must specify archive file" >&2
    exit 1
fi
shift $(($OPTIND - 1))
archive=$1

mkdir -p $tmpdir
tar -x -C $tmpdir -f "$archive"
echo "Differences between archive and repository:"
set +e; diff -r $tmpdir/* "./$path"; set -e
rm -fr $tmpdir
gpg --verify "$archive.asc"
