#!/usr/bin/env bash

get_excluded_submodules()
{
    for i in $(git config user.submoduleskip); do
        excluded_submodules[$i]=1
    done
}

get_submodules()
{
    n=0
    while IFS= read -r line; do
        [[ $line != +* ]] && continue
        submodule=$(echo "$line" | cut -d '+' -f 2- | cut -d ' ' -f 2)
        if [[ ${excluded_submodules[$submodule]} -ne 1 ]]; then
            submodules[$n]=$submodule
            n=$((++n))
        fi
    done < <(git submodule status)
}

get_commit_message()
{
    printf "Commit to submodules\n\nCommit UUIDs:\n"

    for m; do
        (
            set -e
            cd "$m"
            git show | grep "Commit UUID:" | cut -d ':' -f 2 | cut -b 2-
        )
    done
}

if ! declare -A excluded_submodules 2>/dev/null; then
    echo "bash version 4.0 or greater is required" 1>&2
    exit 1
fi
declare -a submodules

set -e

get_excluded_submodules
get_submodules

msg=$(get_commit_message "${submodules[@]}")

git add "${submodules[@]}"
git commit -F - <<< "$msg"
