#!/bin/sh

set -e

rootdir=$(git rev-parse --show-toplevel)
[ $? != 0 ] && exit 1

(
    set -e
    cd /
    exec find "$rootdir" -name '*.c' -o -name '*.h' > "$rootdir/cscope.files"
)

ret=0
if ! cscope -bq; then
    ret=1
fi

exit $ret
