#!/bin/sh

do_make_dist()
{
    cd "$1"

    echo "Generating \"configure\" script" >&2
    autoreconf -v

    echo "Generating temporary makefiles containing archive creation recipe" \
        >&2
    ./configure --disable-dependency-tracking

    echo "Generating archive" >&2
    make dist-xz
    mv -- *.xz "../$archive"

    echo "Cleaning temporary files" >&2
    make distclean
    git clean -fx
    rm -frv autom4te.cache

    cd ..
}

set -e

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" >&2
    exit 1
fi
reponame=$(basename "$(pwd)")

amend=0
automake=0
sign=0
undo=0

while getopts ad:msu opt; do
    case $opt in
        a)
            amend=1;;
        d)
            dstdir=$OPTARG/;;
        m)
            automake=1;;
        s)
            sign=1;;
        u)
            undo=1;;
        *)
            exit 1;;
    esac
done
shift $(($OPTIND - 1))

archive=$dstdir$reponame.tar.xz

if [ $undo -eq 1 ]; then
    if [ $amend -eq 1 ]; then
        git reset HEAD^ "$archive"
        test $sign -eq 1 && git reset HEAD^ "$archive.asc"
        git commit --amend --no-edit
        git checkout "$archive" "$archive.asc"
    else
        git reset --hard HEAD^
    fi
    exit
fi

git config tar.tar.xz.command "xz -9c"
if [ $automake -eq 1 ]; then
    do_make_dist "$@"
else
    git archive -o "$archive" HEAD "$@"
fi
git add "$archive"
if [ $sign -eq 1 ]; then
    gpg -a --detach-sign -o "$archive.asc" "$archive"
    git add "$archive.asc"
fi
if [ $amend -eq 1 ]; then
    git commit --amend --no-edit
else
    git commit
fi
