#!/bin/sh

do_make_dist()
{
    cd "$1"

    echo "Generating \"configure\" script" 1>&2
    autoreconf -v

    echo "Generating temporary makefiles containing archive creation recipe" \
        1>&2
    ./configure --disable-dependency-tracking

    echo "Generating archive" 1>&2
    make dist-xz
    mv -- *.xz "../$archive"

    echo "Cleaning temporary files" 1>&2
    make distclean
    git clean -fx
    rm -frv autom4te.cache

    cd ..
}

restore_files()
{
    mv "$archive.save" "$archive" 2>/dev/null 1>&2
    mv "$archive.asc.save" "$archive.asc" 2>/dev/null 1>&2
}

set -e

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi
reponame=$(basename "$(pwd)")

amend=0
automake=0
sign=0
undo=0

temp=$(getopt ad:msu "$@")
[ $? != 0 ] && exit 1
eval set -- "$temp"
while true; do
    case "$1" in
        -a)
            amend=1
            shift;;
        -d)
            dstdir=$2/
            shift 2;;
        -m)
            automake=1
            shift;;
        -s)
            sign=1
            shift;;
        -u)
            undo=1
            shift;;
        --)
            shift
            break;;
    esac
done
archive="$dstdir$reponame.tar.xz"

if [ $undo = 1 ]; then
    if [ $amend = 1 ]; then
        git reset HEAD^ "$archive"
        [ $sign = 1 ] && git reset HEAD^ "$archive.asc"
        git commit --amend --no-edit
        git checkout "$archive" "$archive.asc"
    else
        git reset --hard HEAD^
    fi
    exit
fi

[ $amend = 1 ] && commitopts="--amend --no-edit"

trap restore_files EXIT
mv "$archive" "$archive.save" 2>/dev/null 1>&2
mv "$archive.asc" "$archive.asc.save" 2>/dev/null 1>&2

git config tar.tar.xz.command "xz -9c"
if [ $automake = 1 ]; then
    do_make_dist "$@"
else
    git archive -o "$archive" HEAD "$@"
fi
git add "$archive"
if [ $sign = 1 ]; then
    gpg -a --detach-sign -o "$archive.asc" "$archive"
    git add "$archive.asc"
fi
git commit $commitopts

trap '' EXIT
rm "$archive.save" "$archive.asc.save"
