#!/usr/bin/env bash

get_commands()
{
    commands=$(git config user.checkCommands)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

get_commands || exit 1

ret=0
IFS=";"
first=1
for c in $commands; do
    if [[ $first = 1 ]]; then
        first=0
    else
        echo "--More--"
        IFS= read -n 1 -r -s tmp
        if [[ $tmp != " " ]]; then
            ret=1
            break
        fi
        IFS=";"
    fi
    cmd=$(eval echo "$c" | sed -e "s/^[[:space:]][[:space:]]*//")
    echo "$ $cmd"
    eval "$cmd"
    echo "\`- $?"
done

reponame=$(git rev-parse --show-toplevel)
logger "Ran check commands for repository $reponame"

exit $ret
