#!/bin/sh

do_exit()
{
    [ "$sign" -eq 1 ] && [ "$agent" -eq 1 ] && killall gpg-agent
    exit "$1"
}

set -e

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi

agent=0
automake=0
distdir=dist
inc=0
sign=0
trunkdir=trunk
undo=0

! temp=$(getopt ad:imst:u "$@") && exit 1
eval set -- "$temp"
while true; do
    case "$1" in
        -a)
            agent=1
            shift;;
        -d)
            distdir=$2
            shift 2;;
        -i)
            inc=1
            shift;;
        -m)
            automake=1
            shift;;
        -s)
            sign=1
            shift;;
        -t)
            trunkdir=$2
            shift 2;;
        -u)
            undo=1
            shift;;
        --)
            shift
            break;;
    esac
done

vfile=$trunkdir/.version

if [ $sign -eq 1 ]; then
    commitarchopts="-s"
fi

if [ $undo -eq 1 ]; then
    git set-version -d "$trunkdir" -tu
    git commit-archive -a -d "$distdir" -u $commitarchopts
    git reset HEAD^ "$vfile"
    git commit --amend --no-edit
    git checkout "$vfile"
    exit
fi

if [ $automake -eq 1 ]; then
    commitarchopts="$commitarchopts -m"
fi

if [ $sign -eq 1 ]; then
    setversopts="-s"
    if [ $agent -eq 1 ]; then
        gpg-agent --daemon --use-standard-socket
    fi
fi

version=$(cat "$vfile")
ret=$?
if [ $inc -eq 1 ]; then
    ! [ $ret -eq 0 ] && exit 1
    maj=$(echo "$version" | cut -d . -f 1)
    min=$(echo "$version" | cut -d . -f 2)
    version=$maj.$((min+1))
fi

set +e

echo "$version" > "$vfile" || do_exit 1
git add "$vfile" || do_exit 1
git commit --amend --no-edit || do_exit 1
git commit-archive -a -d "$distdir" $commitarchopts "$trunkdir" || do_exit 1
git set-version -d "$trunkdir" -t $setversopts "$version" || do_exit 1

do_exit 0
