#!/usr/bin/env bash

set -e

rootdir=$(git rev-parse --show-toplevel)
[[ $? != 0 ]] && exit 1
reponame=$(basename $rootdir)

for i in $(git remotes); do
    case $i in
        bundle_*)
            git remote remove $i
    esac
done

rm -fv $rootdir/../.$reponame.bundle
rm -fv $rootdir/../$reponame.*.bundle
