#!/bin/sh

set -e

tmpdir=/tmp/git_verify_archive

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi

temp=$(getopt p: "$@") || exit 1
eval "set -- $temp"
while true; do
    case $1 in
        -p)
            path=$2
            shift 2;;
        --)
            shift
            break;;
    esac
done
archive=$1

mkdir -p $tmpdir
tar -x -C $tmpdir -f "$archive"
echo "Differences between archive and repository:"
set +e; diff -r $tmpdir/* "./$path"; set -e
rm -fr $tmpdir
gpg --verify "$archive.asc"
