#!/usr/bin/env bash

parse_cmdline()
{
    all_branches=0
    [[ $(basename $0) == "git-make-bundles" ]] && all_branches=1

    if [[ -z $1 ]]; then
        echo "Must specify commit ID"
        return 1
    fi
    commit=$1
    shift

    if [[ -n $1 ]]; then
        branch=$1
    else
        branch="master"
    fi
}

get_repo_name()
{
    local rootdir=$(git rev-parse --show-toplevel)
    [[ $? != 0 ]] && return 1

    reponame=$(basename $rootdir)
}

get_branches()
{
    local tmp

    if [[ $all_branches = 0 ]]; then
        branches="$branch"
        return
    fi

    tmp=$(git branch)
    if [[ $? != 0 ]]; then
        return 1
    fi

    while IFS= read -r line; do
        branches+="${line##??} "
    done < <(echo "$tmp")
}

get_bundle_path()
{
    bundle_path=$(git config user.bundleOut)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

set -e

parse_cmdline "$@"

get_repo_name
get_branches
get_bundle_path

set +e

declare -A branch_excl_set

branches_excl=$(git config user.branchesExcl)
for b in $branches_excl; do
    branch_excl_set[$b]=1
done
branch_excl_set["master"]=1

ret=0
for b in $branches; do
    if [[ ${branch_excl_set[$b]} != 1 ]]; then
        bname="$reponame"
        [[ $b != "master" ]] && bname+=".$b"
        git bundle create $bundle_path/$bname.bundle $commit..$b || ret=1
    fi
done

exit $ret
