#!/usr/bin/env bash

get_remotes()
{
    local tmp

    tmp=$(git remote) || return 1

    for rmt in $tmp; do
        remotes+="$rmt "
        remote_set[$rmt]=1
    done < <(echo "$tmp")
}

if ! declare -A remote_set 2>/dev/null; then
    echo "bash version 4.0 or greater is required" 1>&2
    exit 1
fi

set -e

get_remotes

set +e

remotes_excl=$(git config user.remotesExcl)
for rmt in $remotes_excl; do
    remote_set[$rmt]=
done

for rmt in $remotes; do
    [[ ${remote_set[$rmt]} -eq 1 ]] && echo "$rmt"
done
