#!/bin/sh

set -e

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi

dir=.
inc=0
sign=0
tagonly=0

temp=$(getopt d:ist "$@")
[ $? != 0 ] && exit 1
eval set -- "$temp"
while true; do
    case "$1" in
        -d)
            dir=$2
            shift 2;;
        -i)
            inc=1
            shift;;
        -s)
            sign=1
            shift;;
        -t)
            tagonly=1
            shift;;
        --)
            shift
            break;;
    esac
done

vfile=$dir/.version

[ $sign = 1 ] && tagopts="-s"

if [ $inc = 1 ]; then
    version=$(cat "$vfile")
    [ $? != 0 ] && exit 1
    maj=$(echo $version | cut -d . -f 1)
    min=$(echo $version | cut -d . -f 2)
    version=$maj.$((min+1))
else
    version=$1
fi
if [ -z "$version" ]; then
    echo "Nonempty version string required"
    exit 1
fi

tagopts="$tagopts -m \"Version $version\""

if [ $tagonly = 0 ]; then
    echo "$version" > "$vfile"
    git add "$vfile"
    git commit --amend --no-edit
fi
eval git tag $tagopts v$version
echo "Version $version"
