#!/bin/sh

get_repo_name()
{
    multclones=$1

    if [ "$multclones" = "true" ]; then
        reponame=$(basename "$(dirname "$rootdir")" | cut -d '.' -f 2-)
    else
        reponame=$(basename "$rootdir")
    fi
}

multclones=$(git config user.multClones)

set -e

rootdir=$(git rev-parse --show-toplevel)

get_repo_name "$multclones"

for i in $(git remotes); do
    case $i in
        bundle_*)
            git remote remove "$i";;
    esac
done

rm -fv "$rootdir/../.$reponame.bundle"
rm -fv "$rootdir/../$reponame".*.bundle
