#!/bin/sh

get_repo_name()
{
    multclones=$1

    if [ "$multclones" = "true" ]; then
        reponame=$(basename "$(dirname "$rootdir")" | cut -d '.' -f 2-)
    else
        reponame=$(basename "$rootdir")
    fi
}

get_bundle_path()
{
    bundle_path=$(git config user.bundleIn)
}

get_bundles()
{
    bundles=$(ls "$1/$reponame".* 2>/dev/null)
}

multclones=$(git config user.multClones)

set -e

rootdir=$(git rev-parse --show-toplevel)

get_repo_name "$multclones"
get_bundle_path
get_bundles "$bundle_path"

for b in $bundles; do
    f=$(basename "$b")
    if [ "$f" = "$reponame.bundle" ]; then
        echo "Importing bundle $f" >&2
        mv "$b" "$rootdir/../.$f"
        git fetch bundle
    else
        echo "Importing branch bundle $f" >&2
        mv "$b" "$rootdir/.."
        bname=$(echo "$f" | cut -d '.' -f 2)
        test -n "$bname"
        echo "Creating remote bundle_$bname" >&2
        git remote add "bundle_$bname" "../$f"
        git fetch "bundle_$bname"
    fi
done
