#!/usr/bin/env bash

rootdir=$(git rev-parse --show-toplevel)
[[ $? != 0 ]] && return 1
pushd $rootdir > /dev/null || exit 1

pushd / > /dev/null || exit 1
find $rootdir -name '*.c' -o -name '*.h' > $rootdir/cscope.files || exit 1
popd > /dev/null || exit 1

cscope -bq

popd > /dev/null || exit 1
