#!/usr/bin/env bash

get_excluded_submodules()
{
    for i in $(git config user.submoduleskip); do
        excluded_submodules[$i]=1
    done
}

get_submodules()
{
    while IFS= read -r line; do
        if [[ $line = +* ]]; then
            submodule=$(echo $line | cut -d '+' -f 2- | cut -d ' ' -f 2)
            [[ ${excluded_submodules[$submodule]} != 1 ]] && echo $submodule
        fi
    done < <(git submodule status)
}

get_commit_message()
{
    printf "Commit to submodules\n\nCommit IDs:\n"

    for m in $1; do
        cd $m
        git rev-parse HEAD
        cd - 1>/dev/null
    done
}

set -e

declare -A excluded_submodules

get_excluded_submodules

submodules=$(get_submodules)
[[ $? != 0 ]] && exit 1

msg=$(get_commit_message "$submodules")
[[ $? != 0 ]] && exit 1

git add $submodules
git commit -F - <<< "$msg"
