#!/bin/sh

set -e

force=0
ignore_errors=0

while getopts ef opt; do
	case $opt in
		e)
			ignore_errors=1;;
		f)
			force=1;;
		*)
			exit 1;;
	esac
done

if [ $OPTIND -gt $# ]; then
	echo "Must specify remote" >&2
	exit 1
fi
shift $(($OPTIND - 1))
remote=$1

trunkdir=trunk

vfile=$trunkdir/.version

version=$(cat "$vfile")

test $ignore_errors -eq 1 && set +e

if [ $force -eq 1 ]; then
	git push "$remote" ":v$version"
	git push --force-with-lease --all "$remote"
	git push --tags "$remote"
else
	git push --tags "$remote" master
	git push --force-with-lease --all "$remote"
fi

# vi: set noexpandtab sw=4 ts=4:
