#!/usr/bin/env bash

get_branches()
{
    local tmp

    tmp=$(git branch)
    if [[ $? != 0 ]]; then
        return 1
    fi

    while IFS= read -r line; do
        b="${line##??}"
        branches+="$b "
    done < <(echo "$tmp")
}

do_sync()
{
    ret=0
    for b in $branches; do
        if [[ $b != "master" ]] && [[ ${branch_excl_set[$b]} != 1 ]]; then
            cmd="git checkout $b && git reset --hard $1"
            eval echo \"Running \\\"$cmd\\\"\"
            read -p "Continue? (y/n) " resp
            if [[ $resp = "y" ]]; then
                eval $cmd || ret=1
            fi
        fi
    done

    git checkout master

    exit $ret
}

sync_with_origin()
{
    do_sync "$origin/\$b"
}

sync_with_bundles()
{
    do_sync "bundle_\$b/\$b"
}

set -e

get_branches

set +e

cmd=$(echo $0 | cut -d '-' -f 2-)
if [[ $cmd = "sync" ]]; then
    if [[ $1 = "--bundles" ]]; then
        sync_bundles=1
    else
        sync_origin=1
    fi
fi

if [[ $sync_origin = 0 ]] || [[ $sync_bundles = 1 ]]; then
    declare -A branch_excl_set

    branches_excl=$(git config user.branchesExcl)
    for b in $branches_excl; do
        branch_excl_set[$b]=1
    done
    branch_excl_set["master"]=1
fi

if [[ $sync_origin = 1 ]]; then
    origin=$(git config user.upstreamRemoteName)
    [[ $origin = "" ]] && origin="origin"

    sync_with_origin
elif [[ $sync_bundles = 1 ]]; then
    sync_with_bundles
fi

for b in $branches; do
    if [[ ${branch_excl_set[$b]} != 1 ]]; then
        echo "$b"
    fi
done
