#!/bin/sh

esc_str()
{
    sed "s/'/'\\\\''/g; 1s/^/'/; \$s/\$/' \\\\/"
}

add_to_args()
{
    if [ -n "$args" ]; then
        args="$(printf "%s\n%s" "$args" "$(printf "%s\n" "$1" | esc_str)")"
    else
        args="$(printf "%s\n" "$1" | esc_str)"
    fi
}

set -e

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" >&2
    exit 1
fi
reponame=$(basename "$(pwd)")

distdir=dist
trunkdir=trunk

for i; do
    add_to_args "$i"
done
args=$(printf "%s\n " "$args")

while getopts ad:imst: opt; do
    case $opt in
        d)
            distdir=$OPTARG;;
        t)
            trunkdir=$OPTARG;;
        *)
            exit 1;;
    esac
done

if [ $OPTIND -le $# ]; then
    echo "Unrecognized arguments" >&2
    exit 1
fi

vfile=$trunkdir/.version

echo "0.0" > "$vfile"

mkdir "$distdir"
touch "$distdir/${reponame}.tar.xz"
touch "$distdir/${reponame}.tar.xz.asc"

eval "set -- $args"
exec git prepare "$@"
