#!/bin/sh

esc_str()
{
    sed "s/'/'\\\\''/g; 1s/^/'/; \$s/\$/' \\\\/"
}

add_to_args()
{
    if [ -n "$args" ]; then
        args="$(printf "%s\n%s" "$args" "$(printf "%s\n" "$1" | esc_str)")"
    else
        args="$(printf "%s\n" "$1" | esc_str)"
    fi
}

set -e
cmd=$(echo "$0" | cut -d '-' -f 3-)

for i; do
    add_to_args "$i"
done
args=$(printf "%s\n " "$args")

exec git submodule foreach \
    "$(printf "set -- %s\n; git $cmd \"\$@\"" "$args")"
