#!/bin/sh

set -e

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi

dir=.
inc=0
sign=0
tagonly=0
undo=0

temp=$(getopt d:istu "$@") || exit 1
eval "set -- $temp"
while true; do
    case $1 in
        -d)
            dir=$2
            shift 2;;
        -i)
            inc=1
            shift;;
        -s)
            sign=1
            shift;;
        -t)
            tagonly=1
            shift;;
        -u)
            undo=1
            shift;;
        --)
            shift
            break;;
    esac
done

vfile=$dir/.version

if [ $undo -eq 1 ]; then
    if [ $tagonly -eq 0 ]; then
        git reset HEAD^ "$vfile"
        git commit --amend --no-edit
        git checkout "$vfile"
    fi
    version=$(cat "$vfile")
    git tag -d "v$version"
    exit
fi

if [ $inc -eq 1 ]; then
    version=$(cat "$vfile") || exit 1
    maj=$(echo "$version" | cut -d . -f 1)
    min=$(echo "$version" | cut -d . -f 2)
    version=$maj.$((min+1))
else
    version=$1
fi
if [ -z "$version" ]; then
    echo "Nonempty version string required" 1>&2
    exit 1
fi

args="\"-m\" \"Version $version\""
test $sign -eq 1 && args="$args -s"
eval "set -- $args"

if [ $tagonly -eq 0 ]; then
    echo "$version" >"$vfile"
    git add "$vfile"
    git commit --amend --no-edit
fi
git tag "$@" "v$version"
echo "Version $version" 1>&2
