#!/bin/sh

tmpdir=/tmp/git_verify_archive

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
    echo "Current directory is not root of a git repository" 1>&2
    exit 1
fi
reponame=$(basename $(pwd))

while true; do
    if [[ ($1 == "-p") && $2 ]]; then
        path=$2
        shift 2
    else
        break
    fi
done
archive=$1

mkdir -p $tmpdir || exit 1
tar -x -C $tmpdir -f $archive || exit 1
echo "Differences between archive and repository:"
diff -r $tmpdir/$path ./$path
rm -r $tmpdir
gpg --verify $archive.asc
