#!/bin/sh

restore_files()
{
    mv $archive.save $archive &>/dev/null
    mv $archive.asc.save $archive.asc &>/dev/null
}

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi
reponame=$(basename $(pwd))

temp=$(getopt -l amend d:s "$@")
eval set -- "$temp"
while true; do
    case "$1" in
        --amend)
            amend=1
            shift;;
        -d)
            dstdir=$2/
            shift 2;;
        -s)
            sign=1
            shift;;
        --)
            shift
            break;;
    esac
done
[[ $amend == 1 ]] && commitopts="--amend --no-edit"
archive=$dstdir$reponame.tar.xz

trap restore_files EXIT
mv $archive $archive.save &>/dev/null
mv $archive.asc $archive.asc.save &>/dev/null

git config tar.tar.xz.command "xz -9c" || exit 1
git archive -o $archive HEAD $@ || exit 1
git add $archive || exit 1
if [[ $sign == 1 ]]; then
    gpg -a --detach-sign -o $archive.asc $archive || exit 1
    git add $archive.asc || exit 1
fi
git commit $commitopts || exit 1

trap '' EXIT
rm $archive.save $archive.asc.save
