#!/usr/bin/env bash

get_commands()
{
    commands=$(git config user.checkCommands)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

get_commands || exit 1

IFS=";"
first=1
for c in $commands; do
    if [[ $first = 1 ]]; then
        first=0
    else
        echo "--More--"
        IFS= read -n 1 -s tmp
        [[ $tmp != " " ]] && break
        IFS=";"
    fi
    cmd=$(eval echo "$c" | sed -e "s/^[[:space:]][[:space:]]*//")
    echo "$ $cmd"
    eval $cmd
    echo "\`- $?"
done
