#!/usr/bin/env bash

get_prefix()
{
    prefix=$(git config user.bundleout)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

get_branches()
{
    local tmp

    tmp=$(git branch)
    if [[ $? != 0 ]]; then
        return 1
    fi

    while IFS= read -r line; do
        branches+="${line##??} "
    done < <(echo "$tmp")
}

branch_bundles=0
[[ $(basename $0) == "git-make-bundles" ]] && branch_bundles=1

rootdir=$(git rev-parse --show-toplevel)
[[ $? != 0 ]] && exit 1
reponame=$(basename $rootdir)

if [[ -z $1 ]]; then
    echo "Must specify commit ID"
    exit 1
fi
commit=$1

get_prefix || exit 1
get_branches || exit 1

ret=0
for b in $branches; do
    bname="$reponame"
    if [[ $b != "master" ]]; then
        [[ $branch_bundles = 0 ]] && continue
        bname+=".$b"
    fi
    git bundle create $prefix/$bname.bundle $commit..$b || ret=1
done

exit $ret
