#!/usr/bin/env bash

get_bundle_path()
{
    bundle_path=$(git config user.bundleIn)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

get_bundles()
{
    bundles=$(ls $1/$reponame.* 2>/dev/null)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

rootdir=$(git rev-parse --show-toplevel)
[[ $? != 0 ]] && exit 1
reponame=$(basename $rootdir)

get_bundle_path || exit 1
get_bundles $bundle_path || exit 1

for b in $bundles; do
    f=$(basename $b)
    if [[ $f == "$reponame.bundle" ]]; then
        echo "Importing bundle $f"
        mv $b $rootdir/../.$f || exit 1
        git fetch bundle || exit 1
    else
        echo "Importing branch bundle $f"
        mv $b $rootdir/.. || exit 1
        bname=$(echo $f | cut -d '.' -f 2)
        [[ ($? == 0) && (-n $bname) ]] || exit 1
        echo "Creating remote bundle_$bname"
        git remote add bundle_$bname ../$f || exit 1
        git fetch bundle_$bname || exit 1
    fi
done
