#!/bin/bash

get_prefix()
{
    prefix=$(git config user.bundleout)
    if [[ $? != 0 ]]; then
        return 1
    fi
}

get_branches()
{
    local tmp

    tmp=$(git branch)
    if [[ $? != 0 ]]; then
        return 1
    fi

    while IFS= read -r line; do
        branches+="${line##??} "
    done < <(echo "$tmp")
}

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi
reponame=$(basename $(pwd))

if [[ -z $1 ]]; then
    echo "Must specify commit ID"
    exit 1
fi
commit=$1

get_prefix || exit 1
get_branches || exit 1

ret=0
for b in $branches; do
    bname="$reponame"
    [[ $b = "master" ]] || bname+=".$b"
    git bundle create $prefix/$bname.bundle $commit..$b || ret=1
done

exit $ret
