#!/bin/sh

do_exit()
{
    [ $sign = 1 ] && [ $agent = 1 ] && killall gpg-agent
    exit $1
}

if [ ! -d .git ] && [ ! -f .git ]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi

agent=0
distdir=dist
inc=0
sign=0
trunkdir=trunk

temp=$(getopt ad:ist: "$@")
eval set -- "$temp"
while true; do
    case "$1" in
        -a)
            agent=1
            shift;;
        -d)
            distdir=$2
            shift 2;;
        -i)
            inc=1
            shift;;
        -s)
            sign=1
            shift;;
        -t)
            trunkdir=$2
            shift 2;;
        --)
            shift
            break;;
    esac
done

vfile=$trunkdir/.version

if [ $sign = 1 ]; then
    commitarchopts="-s"
    setversopts="-s"
    if [ $agent = 1 ]; then
        gpg-agent --daemon --use-standard-socket || exit 1
    fi
fi

version=$(cat "$vfile")
if [ $inc = 1 ]; then
    [ $? != 0 ] && exit 1
    maj=$(echo $version | cut -d . -f 1)
    min=$(echo $version | cut -d . -f 2)
    version=$maj.$((min+1))
fi

echo "$version" > "$vfile" || do_exit 1
git add "$vfile" || do_exit 1
git commit --amend --no-edit || do_exit 1
git commit-archive -a -d "$distdir" $commitarchopts "$trunkdir" || do_exit 1
git set-version -d "$trunkdir" -t $setversopts $version || do_exit 1

do_exit 0

