#!/usr/bin/env bash

rootdir=$(git rev-parse --show-toplevel)
[[ $? != 0 ]] && exit 1

ncpus=$(nproc)
[[ $? != 0 ]] && exit 1

if [[ $1 = "-r" ]]; then
    noroot=1
    shift
else
    noroot=0
fi

distdir=$rootdir/dist
tmpdir=$distdir/tmp

mkdir -v $tmpdir || exit 1

tar -x -f $distdir/*.xz -C $tmpdir -v || exit 1

cd $tmpdir/* || exit 1
./configure "$@" || exit 1 # TODO: add option to provide configure parameters
make -j$(ncpus) check || exit 1 # TODO: make building tests optional
if [[ $noroot = 0 ]]; then
    echo "Enter root password to install"
    sudo make install || exit 1
else
    make install || exit 1
fi
make distclean || exit 1
cd - 1>/dev/null || exit 1

rm -frv $tmpdir
