#!/bin/sh

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
    echo "Current directory is not root of a Git repository" 1>&2
    exit 1
fi

distdir=dist
trunkdir=trunk

temp=$(getopt d:ist: "$@")
eval set -- "$temp"
while true; do
    case "$1" in
        -d)
            distdir=$2
            shift 2;;
        -i)
            inc=1
            shift;;
        -s)
            sign=1
            shift;;
        -t)
            trunkdir=$2
            shift 2;;
        --)
            shift
            break;;
    esac
done

vfile=$trunkdir/.version

[[ $sign == 1 ]] && commitarchopts="-s" && setversopts="-s"

version=$(cat $vfile)
if [[ $inc == 1 ]]; then
    [[ $? != 0 ]] && exit 1
    maj=$(echo $version | cut -d . -f 1)
    min=$(echo $version | cut -d . -f 2)
    version=$maj.$((min+1))
fi

echo "$version" > $vfile || exit 1
git commit-archive --amend -d $distdir $commitarchopts $trunkdir
git set-version -d $trunkdir $setversopts
