#!/bin/sh

if [[ ! -d .git ]] && [[ ! -f .git ]]; then
    echo "Current directory is not root of a git repository" 1>&2
    exit 1
fi

dir=.

temp=$(getopt d:is "$@")
eval set -- "$temp"
while true; do
    case "$1" in
        -d)
            dir=$2
            shift 2;;
        -i)
            inc=1
            shift;;
        -s)
            sign=1
            shift;;
        --)
            shift
            break;;
    esac
done

vfile=$dir/.version

[[ $sign == 1 ]] && tagopts="-s"

if [[ $inc == 1 ]]; then
    version=$(cat $vfile)
    [[ $? != 0 ]] && exit 1
    maj=$(echo $version | cut -d . -f 1)
    min=$(echo $version | cut -d . -f 2)
    version=$maj.$((min+1))
else
    version=$1
fi
if [[ -z $version ]]; then
    echo "Nonempty version string required"
    exit 1
fi

tagopts="$tagopts -m \"Version $version\""

echo "$version" > $vfile || exit 1
git add $vfile || exit 1
git commit --amend || exit 1
eval git tag $tagopts v$version || exit 1
echo "Version $version"
